version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ultranx_postgres
    environment:
      POSTGRES_USER: ultranx_user
      POSTGRES_PASSWORD: ultranx_password
      POSTGRES_DB: ultranx_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
